= Community Manager Self-Care
Authors: Ashley Nicolson <ashley@scotlandopensource.com>
Updated: 2020-07-09

== Disclaimer

Materials in this chapter are for informational purposes only, not for the purpose of providing medical advice.
This chapter is not intended as a substitute for professional medical advice, diagnosis or treatment.
Always seek the advice of your physician or other qualified health care provider with any questions or concerns you may have regarding your health both mental and physical.

== Introduction

Because of their roles (but also, perhaps, because of their natures), community managers often focus (even fixate) on the health and well-being of their community members and teams.
They understand the challenges and difficulties associated with encouraging stable, safe, and inclusive online communities, places where people demonstrate compassion and empathy.
But too often, they mistakenly assume they're immune to the same emotionally difficult challenges they strive to help other community members overcome.

What's more, they may even try to _hide_ their vulnerabilities, for fear of being perceived as less capable of performing their roles—or, worse, being rejected by their communities or peer groups group completely.
This perspective on vulnerability can lead community managers down an isolating road, one that might make them feel as though they aren'table to reach out to seek help when they need it.

And yet, the longer we don't attend to our well being, prolonging treatment for our increasingly negative symptoms, the larger the problem—until, eventually, we are mentally and physically debilitated, suffocated, and denied of the fulfillment and joy our role once provided us.
Regaining that joy could take months, even years.
In fact, we may never regain that same level of passion for them again.

To help ourselves as community managers, and in turn help others, we need to learn how to spot the signs of dissatistfaction, disillusionment, and burnout.
These signs can be subtle and hard to detect, but by identifying and acknowledging these changes in behavior (first and foremost in yourself), you begin applying similar awareness to others in your communities.
This experience can provide insight to developing and building up social norms and mechanisms for the community to help reduce the occurrence and impact of burnout thus promoting a physically and mentally healthy, more productive community.

_In this chapter, we'll ..._

== The importance of self-care

What exactly is self-care?

The WHO (World Health Organization) defines self-care as:

____
"Self-care is the ability of individuals, families and communities to promote health, prevent disease, maintain health, and to cope with illness and disability with or without the support of a healthcare provider".footnote:[World Health Organization, https://www.who.int/news-room/fact-sheets/detail/self-care-health-interventions[website]]
____

In a nutshell, then, self-care is the practice of making conscious, mindful efforts to perform activities that aid in our physical, emotional, relational, and perhaps spiritual well-being at a fundamental level.
Most of us already practice self-care daily by taking actions to protect our overall health (for example, eating healthily, exercising, and getting enough sleep).
Sometimes, however, we may find acts like these alone are insufficient for maintaining our well-being—and that a conscious effort at finding additional support is required.

We can usually handle stress more effectively when we're in a happy state in mind.
So by practicing self-care, we can build a resilience to life's unavoidable stressors.

This concept of self-care may appear simplistic in theory, but it is so commonly overlooked or neglected—especially by community managers.
Let's explore (and deconstruct) some reasons why.

=== Emotional contagion

Community managers are often seen as leaders, the people everyone can turn to, an inspiration for others to emulate.
This seemingly high pedestal can be daunting, demanding a good deal of emotional intelligence and mental effort to deliver a community that's not only growing but also productive.footnote:[The Community Roundtable, https://communityroundtable.com/state-of-community-management/burn-out-risk-is-high-for-online-community-managers/[2019 State of Community Management Survey]]

When the going gets tough, it's often our responsibility (and our desire) to pull the community through those times.
But in order to do this, we need to be in top condition _ ourselves_.
That is, we first need to look after ourselves before we can look after others in any sustainable way.
Otherwise, we'll never be able to adequately face whatever is thrown at us (and, when interacting with diverse personalities, resolving conflicts, making tough decisions, and all the while working towards future long term objectives, something always is).
And that is why self-care is so important.

One of the first tasks on the road to self-care, then, is to be aware of how our own emotional states can impact our communities.

Emotions (both positive and negative) are highly contagious.footnote:[Sherrie Bourg Carter Psy.D, https://www.psychologytoday.com/us/blog/high-octane-women/201210/emotions-are-contagious-choose-your-company-wisely[Emotions Are Contagious - Choose Your Company Wisely]]
Our emotional expressions have the power to unconsciously influence people around us, such that others may even begin unconsciously mimicking our own.footnote:[Principles of Social Psychology, https://opentextbc.ca/socialpsychology/chapter/the-role-of-affect-moods-and-emotions/[The Role of Affect: Moods and Emotions ]]
If we are in a state of anxiety or stress, others will sense this and add to it their own negative energy.
We see this when dealing with particularly toxic community members infecting others, but fail to identify that we ourselves can unconsciously unduly influence others as well.
Similarly, if we are in a genuine pleasant mood, then people tend to be driven by that positive mood and become more productive.

In short: In order to bring out the best in others we must bring our best to the table.

As leaders, we wield potentially immense power to make positive changes in our communities.
Let's use this power.
Take every opportunity to utilize your influence for encouraging and promoting self-care—not only for the community's benefit, but also for yourself.
Educate yourself on what self-care looks like to you, and communicate that understanding with your team.
Community managers don't need to share their most intimate fears or anxieties.
Yet simply initiating a conversation on the importance of self-care can be beneficial, not just for the team _running_ the community, but for the _entire_ community.

Identify and implement regular, dedicated time in your and the team's workload to practice self-care.
Set realistic expectations on deliverables and communicate frequently within the team potential triggers of stress or strain that may require more downtime to focus on one's physical and mental health.

By taking steps towards actively promoting and advocating for self-care, you prompt members following your lead to do the same. You also begin revealing your human side, eroding the unhealthy addumption that leaders are invulnerable to emotional dimensions of the work.

=== Being human

We can often find ourselves being controlled by our own, or by other's, generalization of what a community manager should be: driven, friendly, successful, super human, or perfect even.

However, the list of what a leader should be is long, contradicting and often fundamentally flawed.
A leader can be many things to many people but the most important aspect is that they are human: flaws and all.

We tend to over compensate, trying to live up to the wrongly perceived image of a leader, by suppressing or hiding our negative emotions in fear of being seen as too emotional or worse, being out of control.

There is a difference of being in control, under control and being controlled.

Believing that being in control is a reflection of our confidence in what we produce, is inaccurate.
It actually demonstrates that we are reluctant to show others that we are not perfect and struggle to accept anything less.

Although maintaining this front can help shield us temporarily from others' emotions and criticisms towards us, it doesn't protect ourselves from our own self-destruction caused by bottling them up.

Consequences of suppressing your emotions is that they will inevitably surface and dramatically so.
This is when our emotions control us and our actions, which often leads to rumination, break down of relationships with the team or community and other negative outcomes including burnout.

The ultimate aim is to be "under control" in your leadership, emotions and workload.
Our passion and attention is directed in a constructive and purposeful manner, this being especially important after when a mistake is made.

The phrase "bring your whole self to work" is a good expression of allowing yourself this forgiveness.
We feel we can admit when we don't know something, the right decision or simply acknowledging when we've made a mistake.
But it also can be applied to recognizing and accepting that we can have good and bad days.

Being honest with ourselves is as important as being honest with the community.
Needing to admit that we may not be at our best and detracting yourself from unintentionally escalating  difficult situations into becoming worse situations would be the best choice to make at those times for the community.

This emotional labor can be extremely exhausting to maintain.
We must acknowledge and accept that being perfect is unattainable, and more importantly, not required to be the best leader.
What is important is that people can relate to your human side.

People gravitate to those that they share a kinship with and being able to identify this is one of the characteristics of a good community manager.
If your members see that you have qualities that they can relate to, it helps them to more easily empathize with you.
Funnily, we usually try to highlight the significance of our empathy for our members or team, but it's equally important that our members demonstrate compassion, and gratitude to us too.

Nurturing this empathy, from both sides, will help to develop deeper connections and trust between members and team, which in turn can help establish an informal social support network.
This network can be a conduit to promoting the importance of self-care, creating judgment free zone or providing safe havens to individual members, including yourself, to reflect on emotions, frustrations or workload.

It is inevitable that some members will expect you to adhere to the pretense of being the all powerful, infallible captain of the ship, but with an effective self-care routine and the backing of the members within the social support network you will be able to feel more confident in yourself to handle those stressors and that your vulnerabilities are what makes you a better leader to the community.

== Types of Self-Care

Self-care is unique to each person as well as depending on our moods and circumstances.To be effective it requires regular and conscious cultivating, so its important that self-care is not seen as only a reactive choice but a means to help break down stress from every day life.

There are a number of different types of self-care that aim to satisfy our basic( as well as deeper) needs to promote a healthy and happy mind and body.These are: *physical*, *mental*, *spiritual*, *emotional*, and *social*.

It is important to remember that we should be aiming to practice a selection of activities from all types to provide yourself a good balance to help you adapt to all types of stress.

=== Physical Self-Care

Physical is usually the self-care we often do at a minimum subconsciously: feeding, hydrating, sleeping and regular exercise.

However, we often find ourselves neglecting these necessities for the sake of work, like for example having frequent all-nighters, or forgetting to eat lunch every weekday.
Keeping ourselves nourished helps maintain a healthy body as well help us stick to having regular breaks from your work, or environment.

A few examples of physical self-care:

- Regular sleep routine
- Aim for a healthy diet
- Taking a nap
- Getting a massage
- Going for a stroll
- Stretching
- Yoga (or other forms of exercise)

=== Mental Self-Care

Mental self-care is the act of stimulating our mind with positive and purposeful thoughts to help reduce stress levels.

These are doing things that keep the mind engage at an intellectual level on topics that interest you or help de-clutter your thoughts to re-organize them.

Mental self-care is often less tangible than other types so it can be more difficult to see an immediate benefit.

However, with consistency of exercising mental self-care we will see it's benefits shape and form healthy attitudes towards others aspects of our life as we will be more inclined to be mentally satisfied.

A few examples of mental self-care:

- Reading a new book or article
- Try a hobby or interest
- Write a list of goals
- Solving puzzles
- Organize or clean out a space in your room

=== Spiritual Self-Care

This type of self-care often gets wrongly associated with being solely religion but it can be applied to everyone whether you're religious, atheist, agnostic, or otherwise.

Spiritual self-care are activities that nurtures the connection between you and your soul, providing you a deeper sense of meaning, or understanding of the universe.
The word soul is merely a representation of the entity or uniqueness you feel embodies you, this can also be your inner spirit, energy source or another reference.

A few examples of spiritual self-care:

- Volunteering for a cause you care about
- Meditate
- Spent time in nature
- Pray or attend religious service
- Determining your most important values or morals
- Considering your significant relationships
- Discover new forms of spirituality and religion


Regardless of the different types and activities of self-care you perform, the aim is to help us in a constant and sustainable way, to fight off and defend us against the negative effects of our role.
By ignoring our physical and mental well being we will be more likely to succumb to the stress and fatigue leading us towards more dangerous chronic illnesses and syndromes, like burnout.

== Burnout

What exactly is burnout? The WHO (World Health Organization) definition of burnout is:

> "Burnout is a syndrome conceptualized as resulting from chronic workplace stress that has not been successfully managed. ".footnote:[World Health Organization, https://www.who.int/mental_health/evidence/burn-out/en/[website]]

Burnout can affect us all and in any occupation, however it seems more prevalent in roles that are mentally and emotionally draining for extended periods of time.
This is common due to the prevailing norms within those roles of being selfless and putting others first.footnote:[Herbert J. Freudenberger, https://spssi.onlinelibrary.wiley.com/doi/abs/10.1111/j.1540-4560.1974.tb00706.x[Staff Burn-Out]]: going the extra mile to maintain a happy and content environment or atmosphere either for the client or within a community.

It is also appearing more and more within the tech industry.footnote:[Team Blind, https://www.teamblind.com/blog/index.php/2018/05/29/close-to-60-percent-of-surveyed-tech-workers-are-burnt-out-credit-karma-tops-the-list-for-most-employees-suffering-from-burnout/[Close to 60 Percent of Surveyed Tech Workers Are Burnt Out...]] 
This increase has been attributed to the seemly accepted 24/7 work mentality and competitiveness of the industry, leading to workers involved in technology, particularly software development, to becoming overwhelmed and mentally exhausted to the point of risking their health.

We should highlight that work related stress and burnout are very different, and in cases some amount of stress can provide a source of motivation but only if it is manageable and for a temporary period of time.
When occupational stress is long occurring, seen as chronic, affecting the overall well being of ourselves, this can develop into the term of burnout.

=== Look out for symptoms

Burnout is extremely hard to detect as not only is it subtle and progressive, but it is often misdiagnosed as the earlier, more temporary, common work related stress.
This is because the two are similar until it becomes too late and has developed into a much deeper and harder problem to treat.

Psychologist Herbert Freudenberger has released multiple books and articles regarding his research of the possible causes, implications and affects of burnout since the 1970's.
His work.footnote:[Dr Herbert Freudenberger and Geraldine Richelson, "Burn-out : The High Cost of High Achievement"] has helped to define the different symptoms and thus the phases of experiencing burnout.

Perhaps you recognize several of them in yourself; perhaps you recognize only one or two.
It's not always easy to see the signs since not only do they gradually occur over time, but also hide behind our own denial of something being wrong.

*Exhaustion*

Loss of energy and accompanying feelings of weariness are usually the first distress signals especially when, being a community manager, we naturally have high energy levels.footnote:[Maslach, C., & Leiter, M. P. (2008), https://doi.apa.org/doi/10.1037/0021-9010.93.3.498[Early predictors of job burnout and engagement. Journal of Applied Psychology, 93(3), 498–512]]
However, be careful not to push yourself harder if you do find yourself struggling to keep up with your usual round of activities. 
Doing so will only exacerbate the problem.

Similarly to our emotions, our energy also affects others around us.
We tend to fuel our energy by achieving our goals and reaping the rewards, thus sharing that with others.
If we are unable to attain rewards due to the lack of energy levels then this feeds into a vicious cycle.

The things that once excited us, like leaving a meeting fired up to accomplish an objective, have now become mundane and seen as excessive use of our already depleting energy.
You may not see the lack of accomplishments, like others do, because you see less and less significance in obtaining the rewards and blame your tiredness on your increasing workload.

*Detachment*

We usually demonstrate a sense of detachment or apathy as a self-protective device to help ward off emotional stress or pain.
When we begin to feel let down by situations or those around us, whether that is the team, community, company or even ourselves, we are temped to down play their importance; "I don't care, it wasn't important anyway" and move away from the things that used to involve us.
By doing so we are depriving them the power to affect us negatively, however, this also blocks their ability to positively affect us.
This can lead to loneliness and isolation.
 
*Boredom and Cynicism*

Once you've become more detached from the things that excited you, you find it increasingly hard to remain interested in what's going on around you.
You begin to question the value of your activities, your relationships, and perhaps the bigger aspects of your life.
This can lead you to becoming skeptical or even suspicious of other people's motives and causes.

*Impatience and heightened irritability*

People who have high energy levels also usually have a characteristic of being mildly impatient, whether it is with others or with themselves, due to their ability to perform things quickly to then progress onto something else.
However, when experiencing burnout, the perception that we need to over accomplish things and thus so does the impatience to do so.
This impatience can spill out over to others as irritability with everyone around them.
Things that were once trivial and minor become huge obstacles often with the blame pointed at others creating it rather than ourselves.

*A sense of omnipotence*

We don't start off feeling this way about our role, but often when we are overwhelmed with our workload we can default to a sentiment "No one else can do this, only I can."

This sort of statement is often an attempt to justify the over exertion of the effort and applying value to it whilst other areas of our workload is failing.
That grasp of control when things are becoming out of control.

Rest assure that indeed others can perform those tasks, though differently and maybe not to the same degree of excellence you may have done but it could be a situation that doesn't always require excellence.
This type of egoism is more often a hindrance to progression and the initiative of others.

*A suspicion of being unappreciated*

To counter balance our lack of energy we often increase our effort, but this doesn't necessarily reflect good results.
However we don't acknowledge this, we only see the effort expended.
We can then begin to feel like we're being less appreciated from others in the team or the community as a whole.
"Can't they see all the hard work I'm doing, staying late at night?" 
This feeling can lead to being bitter and angry.

*Paranoia*.footnote:[ R Bianchi, L Janin https://academic.oup.com/occmed/article/69/1/35/5151234[Burnout, depression and paranoid ideation: a cluster-analytic study]]

Leading from the signs of feeling unappreciated to feeling as though the world is against us.
When things go wrong, but we are unable to understand or see why, we tend to seek out a target, not ourselves, to blame regardless if there is little merit in the accusation.
Often the person labeled as the culprit becomes the target of our frustrations.
This can be team members, friends or even family.

*Disorientation*

Disorientation is when we feel we've become separated from our environment and understanding of what is going on around us.
Discovering yourself in a situation that you didn't become aware of or that you previously understood a concept but now do not.
We see ourselves starting to forget things easily and our concentration span deteriorates leading us into more confusion and agitation, fueling the other symptoms like paranoia.

*Psychosomatic complaints*

This is not to be misunderstood that implying those experiencing signs of burnout are not feeling physically sick, they can and do.
But it does highlight that with prolong stress physical illness symptoms appear as a secondary symptom to the cause, like linger colds, backache, headaches etc.
Sometimes these illnesses mask the deeper more emotional stress that we feel but we feel more comfortable taking a sick day instead of actually acknowledging the mental stress.

=== Burnout cycle

Freudenberger and his colleague Gail North.footnote:[Dr Herbert Freudenberger and Dr Gail North, "Women's Burnout: How to Spot It, How to Reverse It, and How to Prevent It"] later categorized the consequences of these symptoms into 12 phases of one developing burnout syndrome.footnote:[Freudenberger's 12 stages, https://www.burnoutgeese.com/freudenberger-burnout.html[Freudenberger's 12 stages]].
Similar to the symptoms, sufferers may experience episodes in multiple phases, not in sequential order, and for any length of period of time.

. *A compulsion to prove oneself*: desire to prove oneself, to have impact on one's peers, initially seems beneficial until this desire turns into obsession.

. *Intensity (Working Harder)*: compulsion becomes misconstrued as dedication and commitment. This can appear as an unwillingness to delegate work, for fear of losing perfect control, or working harder and longer.

. *Neglecting their needs*: work begins to dominate and subtler duties and pleasures are viewed as unnecessary like sleep, eating healthy, etc.

. *Displacement of conflicts*: conflict from others are considered meddlesome and seen as a threat. Coping mechanisms are put into place to dismiss problems and these can manifest into physical breakdowns.

. *Distortion of Values*: focus on work only, values are distorted as well as relationships. This leads to them being dismissed or abandoned. 

. *Denial of Emerging Problems*: mechanisms to defend oneself against the impact of life and in turn their demands. Develop inability to tolerate ambiguity and become non-receptive; projecting the anxieties and insecurities externally. 

. *Withdrawal*: Become detached from our emotions and from other people. Often "escaping" through television, books or other means like alcohol/drugs.

. *Odd Behavioral Changes*: friends and family identify increasingly obvious changes in behavior like attitude, language or physical activities.

. *Depersonalization*: viewing the needs of one self and others are now significantly undervalued and dismissed.

. *Inner Emptiness*: feelings of hollowness and uselessness. There is a desire to replenish but are usually quick wins, or false cures and ultimately unfulfilling.

. *Depression*: feeling of being hopeless and joyless. Despair and exhaustion are primary feelings and the overwhelming desire to escape.

. *Burnout Syndrome*: suicidal thoughts, physical and mental collapse leading to life threatening situations. Immediate professional medical help is imperative.

These distinctions help us to identify the deterioration in either our own, our team's or community member's activities and their attitudes towards themselves and others. 

It's important to be self-critical and pierce our disillusion that everything is fine – it usually isn't and it won't "just work its way out".

=== Causes of burnout

We've identify the devastating affects of burnout now lets explore the possible sources to these symptoms within our role or even within the community. 

We earlier described that burnout is a combination of many factors but a recurring element is the realization, subconsciously or not, that we don't feel our work is providing us the same sense of reward and purpose as it had once done before.footnote:[Adeva https://adevait.com/blog/workplace/burnout-tech-industry#2-what-causes-employee-burnout-in-the-tech-industry[What causes employee burnout in the tech industry]]
Rewards doesn't always equate to money or status but can simply be the deeper satisfaction and pleasure in the adhering to one's values and achieving happiness.

*Lack of Control*

To feel a sense of accomplishment and ownership of a task, a role requires a suitable level of autonomy to achieve this. 
If we have the inability to influence our decisions or don't have access to appropriate tools or resources, this can lead to the de-motivating feeling that our work and effort is not being appreciated enough or we are not trusted enough with this responsibility.

Lack of control can also manifest when dealing with other peoples' emotions.
Although we can encourage and try to direct our members to adhere to our community's code of conduct or a preferred course of action in a conflict, we evidently can not remove their willfulness.
We must only pre-empt their next move no matter how disastrous it may be.
This can lead to the feeling of constantly fire fighting and not accomplishing anything.

*Unfairness*

Unfairness within the role can be viewed as a number of different things that attribute to one's feeling powerless or being disrespected.
Either you or others are treated unfairly: office or community politics that creates a culture of favoritism, lack of transparency in the top down decisions, or a disproportionate amount of workload is allocated to you.

*Insufficient Reward*

You feel unappreciated, taken for granted or simply not satisfied in your role.
Rewards don't always require to be monetary but often this is the first thing to come under our scrutiny when the workload increases.

We also need social rewards where we gain the recognition from others.
A lack of recognition can be from the our company itself not appreciating our worth: the team's lack of respect towards us, or from the community not seeing all the "behind the scenes" activities we perform.

Intrinsic rewards are also important to maintain a healthy perceptive on our role.
This is where you take the self-acknowledgment of doing a good job and feel accomplished.
When we feel we aren't living up to our standards we begin to feel disappointed and become de-motivated.

Sometimes we feel unsatisfied because we have a conflict of personal values with the company or project we work with.
We are often asked to relay and even promote the decisions of the company to the community and these may not align with our own personal values.
This can be seen as self-betrayal to your morals and build up resentment towards the company.

*Work Overload*

Probably the most common experience attributing to burnout is the over burdening of one's workload.footnote:[The American Institute of Stress: Survey, https://www.stress.org/workplace-stress[The AIS Workplace Stress Survey]], whether from our own doing or by someone else.
This can occur when the quantity of work and expectations exceeds the amount of time or resources available.
We often find that most other employees expect work attributed to yourself is "urgent" when in fact they aren't.
It's important to maintain boundaries and stand your ground to combat an ever increasing list of things to do.

*Lack of Community*

It goes without saying that community is extremely important; its fuels the purpose of the role as a source of motivation and companionship - a sense of belonging to a person.However if this becomes stagnant, overwhelmed with toxic members and feedback is non-existent this can make the job feel stifled.

=== Preventing/Treating Burnout

If you feel yourself or anyone else succumbing to burnout then the most direct approach is to take a break from the source of the stress, which is more often work, and reflect on the more acute causes of your burnout.footnote:[Pyschology Today, https://www.psychologytoday.com/us/blog/high-octane-women/201109/when-life-loses-its-meaning-the-heavy-price-high-achievement[When Life Loses Its Meaning: The Heavy Price of High Achievement]] 

*1. Use your holiday time*

Don't be afraid to utilize this time and don't feel guilty either. 
Using your holiday does not demerit your dedication to the role, neither does it mean that everything will fall apart whilst away. 
Use this time to concentrate on yourself, and what gives you pleasure in life.

*2. Spend time with those you care about*

Re-kindle your social relationships, they have probably missed you as a result of the developing burnout. 
Talk through how you're feeling and enjoy your time with them so it is overall a pleasant experience. 

Try to generally stay clear of negative people in your life. 
This could mean letting them disappear from your social network, or limit your interaction with them. 
Remember, other people's emotions can affect us both positive and negatively. 

*3. Re-evaluate priorities*

Identify what is important to you and reflect upon if your current lifestyle, or work life balance mirrors that. 
If they don't then priorities what you wish to enjoy more and block out time in your schedule and commit to it.

Also evaluate your options and consider what the next steps would be to resolve the stressors you have. 
This could be coming to a solution or compromises with your line manager to reduce workload or other concerns you have. 
There may be a point that the only way to remove certain stressors in your life is to leave your job to improve your health.

*4. Practice self-care*

Take the time to commit yourself fully to what ever self-care activity you want to enjoy and do it. 
Try and practice self-care daily, detaching yourself from as much work as possible and devote yourself to some "me" time. 

*5. Seek professional help*

If all the other options have little or no affect on your physical or mental well being, or you feel you require immediate assistance, then do seek professional help as a matter of urgency.

== Work Life Balance

A healthy work life balance is having a clear distinction between our personal and work lives without allowing one to dominate the other. Both are equally important and neither should be undervalued.
We can find ourselves in unhealthy mindsets when forced to be stuck in either one extreme or the other withholding an important sense of purpose and enjoyment from that part of our lives.

It has also become more difficult in this day and age to detach ourselves physically from our work life. 
Technology has provided us such a convenience that we are in almost constant connection to it, and thus in connection to our online communities. 
It is a common place to check emails at all hours, or respond to members of communities on our social media network.

As well as this physical difficulty we may also have the emotional difficulty of switching off from work as well. 
We can feel that it's a requirement of our role to be available 24/7 and be responsive as a reflection of a caring and active community. 
This is often not the case and that in fact is counter productive in building a sustainable community and providing quality interactions with our members. 
Leaders don't need to respond to all messages to be great.

Each person's work life balance is different with each their own prioritizes. 
This is where self-care activities play a big part in establishing the distinction between work and personal life. 
Make a clear differentiation of what you view as work, like answering community requests or emails, arrange calls or meetings etc and the hours that you aim to dedicate those to, anything outside of that communicate to yourself and to others that is your personal time.
By dedicating a consistent and explicit downtime, we begin to develop a habit that our body and mind anticipates and begins to look forward to thus easier to develop a good habit to maintain.

=== Addiction

Work addiction, often referred to as workaholism, can affect anyone who is deeply embedded in an online community and often justifies their extensive work hours as commitment to the project. 
The inability to stop is often driven by the compulsive need to achieve status and success, or in some cases to escape emotional stress. 
Work addiction can be a vicious cycle where the feeling of achievement is an addictive "high" at the cost of our mental and physical well being, often not noticed until too late.

Work addiction, like others addiction, there is a great difficulty with acknowledging there is a problem to begin with. 
People suffering from work addiction are often in denial, convincing themselves that work is a pleasure. 
However, eventually this over compensation of effort and time, neglect of personal relationships and well being, leads to the inevitable experience of burnout.

It's important we develop a healthy relationship with our role itself without feeling the need to be on the pedal at full gas. 
Try and assess what truly drives your motivations to achieve and does this require you to be online the amount of time you are. 
Do you find that you feed off external praise as form of validation of your work? 
Do feel that if you walked away from the community it would fall apart? 
Identify those moments of pleasure, whether it's ticking off a task, or receiving a compliment from a community member or boss, and evaluate whether or not they are needed in the same doses you are currently experiencing them at.

We can also find that this need to achieve is a reaction to a heavy workload from the lack of resources within the team trying to prove to others the value the role and team brings to the project or company. 

Reconsider these goals with the aim to reduce your workload. 
Are they achievable and maintainable with the current resources without sacrificing quality and a good work/life balance? 
If they aren't then consider prioritizing and communicating the most impactful goals that the team can achieve. 
Delegate any other tasks to suitable members or establish more flexible timelines, and anticipate time for possible firefighting as part of those deadlines.

Not only does this help to set reasonable expectations for the team members to achieve, but also promotes that a healthy work/life balance is an integral part of their schedule. 
This predictable schedule also helps you to provide better forecasting to the company or community.

=== Maintain boundaries

When reflecting upon our work life balance, it is important to establish clear boundaries between the two. 
As we've said earlier that due to our nature of work, we find ourselves participating within the community and this begins to eat into our personal time leaving nothing else. 
This is tolerable only on a temporary basis and only when we are required for an intervention, but this should not be the norm. 
Boundaries help us establish where our work ends, and pleasure begins. 
We're not saying that work isn't pleasurable, but having a variety of activities other than work helps stimulate our minds and provide alternative creative outlets.

These boundaries can also help the community acknowledge and accept your expectations of them as well of what they can expect from you. 
Be as transparent as possible by defining your available hours, an escalation process and highlight the importance of documenting community processes so members feel more informed on what they should do in incidences with or without requiring assistance. 
The aim is to establish a consistent schedule and the team and community to respect it. Although they may not do so on every occasion, you will be able to use your boundaries to help combat the feeling of guilt as you begin to embrace personal time as your own as well as respecting others.

Of course if there are any serious incidences that requires your intervention during down time ensure you put into place mechanisms for the team to combat them rather than yourself being the only one who ‘can handle it'. 
These mechanisms can be an escalation process or a team effort to respond and review the response collectively. 
This helps encourages the mentality that everyone can lighten the load especially when it eats into yours and their personal time.

Maintaining personal boundaries is also extremely important as well. 
Our role often asks us to help members with their workload but also interpersonal communication on matters either between other team members. 
But we need to be aware and recognize that we can't solve every interpersonal issue or conflict – sometimes we just can't become too involved.

As much as we don't want to admit it, we must respect that we are not skilled or obligated to practice therapy if we feel it is required for a particular member. 
When the conversations or observations become more apparent then aim to persuade them to seek medical or psychiatric help. 
Our role is to aid members, but there is only so much we can achieve from our position and that is OK.

It can be beneficial to par-take in mental health training for you and your team to learn how to handle situations involving members in the community or team. 
This can help you apply a suitable process to follow upon if someone is beyond your ability and responsibility to help them.

=== Sustainability

Sustainability is an extremely important goal to have for a community, often seen as a contributing factor to the project's own success. 
This should always be at the forefront of our minds when developing tools and processes for the community with the aim for it to become self-reliant, self-driven and empowered.
But there is a lot of work to be done to achieve this, and we need to ensure we and our team are able to keep up. 

Things become unsustainable when we have set unrealistic expectations either upon  ourselves or on the community. 
When it comes to ourselves we can under estimate our project timelines because we have attributed our motivation as part of the estimation: the drive that will get us over the last hurdle. 
Motivation is not on unlimited supply and can fluctuate drastically due to external and internal factors. 
Try to extract motivation as a factor, although you may feel extremely excited about a project, don't let that cloud your judgment on how long a project will take to complete. 
If not, you may see it negatively affecting your work life balance.

We tend to also inaccurately assume the motivation of others in the community. 
By definition community member are volunteers and yes we are fortunate to have those exceptional members that go above and beyond what is required. 
However, we should not expect the same of all, in fact we should expect delays and anticipate them. 

By beginning to form clear boundaries, reduce your workload expectations, and improve estimations you start to deliver on realistic schedules. 
Say you achieved a task within a week, rather than it taking triple that amount of time because you identified it as a priority; delegated other lower tasks to the team (or set the expectation it wouldn't done at all); only worked within your allocated time; and were refreshed from recharging your mental well being with dedicated offline time. 
This combination of activities and processes was key to achieving success thus triggering the event of providing and receiving continuous rewards and helping towards reducing the probability of members developing burnout.

The only thing that is ever consistent is time so be aware that you may find the same rewards you gave yourself and others, change over time. 
Take time out to frequently reflect what drives you and your community, positively review how much you have progressed and assess what resources you have to adjust project goals accordingly without interfering, if possible, with a healthy work life balance.

== Self-Reflection

=== Through the looking glass

An important aspect of being a manager is to provide good and constructive feedback to those that are on our team, as well as the community as a whole. 
We understand that feedback from upper line managers and those that report directly to us is extremely important to understand their perception of us as a person and our activities representing them: if they truly reflect our efforts.

Retrospectives are now almost integral in software development teams to try to continuously improve an individuals or team performance, morale and identify problems that need solving. 
However we find we don't often do them for ourselves, with ourselves. 

Introspections are the examination of one's own conscious thoughts and feelings. 
This can refer to the mental state or in a spiritual sense, one's soul. 
Self-reflection, introspections and self-care are all intertwined with the aim to promote and sustain a positive direction for mental growth and development.

Introspection is extremely important for ourselves to evaluate our purpose and happiness we get from our actions, thoughts and behavior. 
Work is an extremely big part of our lives so ensuring that our role, not only within the community, but the company itself, their values align with ours. 
Else we will find ourselves becoming more and more dissatisfied by the role's insufficient rewards.

But first we need to know what our values are, what qualities we you enjoy of the role and the characteristics of the people we love to work with. 

Take some time to truly answer these as gaining this self-awareness does not happen over night.
Use them to help you reflect on how you feel when you do the things you do, both positively and negatively. 
Journaling is often a good, yet simple, practice you can do to clarify your thoughts.

Practicing self-reflection can be difficult to begin with due to previously discussed inner restrictions we place upon ourselves as community leaders: the need of being invincible; distorted perception of our worth; and lack of visible support. 
However creating a routine of introspection and self-reflection as part of our self-care we will begin to exercise more control over our emotions: have inner clarity on our long term goals, and ability to identify more solutions-focused activities rather than the previously emotionally driven ones.

=== Tackling Imposter Syndrome

This term was first defined by psychologists Dr Pauline Clance and Dr Suzanne Imes.footnote:[Dr Pauline Clance and Dr Suzanne Imes, "The imposter phenomenon in high achieving women: Dynamics and therapeutic intervention."] in the 1970's as the internal experience one feels, despite overwhelming amount of evidence proving other wise, that they are incompetent and that their success was a product of luck or fraud within their field of expertise.

Often those that experience impostor syndrome have a hard time internalizing and accepting their success by minimizing positive feedback and comparing other's work to their own. 
This more frequently happens if we have started a new job, take on new responsibilities or role, or returned from a recent career break. 
In order to compensate for this chronic self-doubt we begin to work late, procrastinate or try and justify our position in unnecessary ways.

Dr Valerie Young.footnote:[Dr Valerie Young, "The Secret Thoughts of Successful Women"], further categorized these types of flawed thinking of what sufferers believe it takes to be component into the following subgroups:

*Perfectionist*

Perfectionism and Imposter syndrome tend to go hand in hand. 
When a perfectionist doesn't achieve their unreasonable high standards they question their abilities and thus if they deserve to be in the position they are in. 
If they do successfully achieve their goal, there always seems to be that unattainable objective they expected to have reached or knowledge they expected to have but didn't.

*Natural Genius*

These sufferers feel that the natural ability to achieve a task is a direct correlation to their competence. 
If they take a long time to master something they feel that it has less merit. 
Not only do they have high standards but they also have to complete it without breaking too much of a sweat.

*Soloist*

These are those that shy away from asking for help because they fear that would expose them for who they believe others to see them as – a fraud. 
Although being independent is good, it can lead to sub par results without acknowledging that two heads are often better than one. 

*Expert*

People with this complex of impostor syndrome often dismiss their success because they don't know everything there is to know about the topic or role. 
Often these people dislike to be put on the spot in case there is some aspect they were unaware of and thus exposed as a fraud.

*Superhuman*

Usually these people often over compare themselves to others in their industry, the seemly high achievers, and push themselves to work harder and longer to measure up to them. They also tend to heavily rely on external validation.


Since our role as community managers is relatively new and less established than other roles within the tech industry we can find ourselves struggling to easily define and confirm our decisions due to the lack of expertise and documentation in this field. 
We can find ourselves feeling more aware of being identified as a fraud especially when the company or project has never had a community manager before.

However, there are ways to help keep impostor syndrome in check and increase your self confidence.

*Celebrate Successes*

Frequently write down our successes and enjoy them. 
Journaling is a good way to have comparisons from earlier successes and how they lead up to our current ones. 
Include our own account of successes but better yet include testimonials from others, be it from community members responding to our thread posts, or colleagues praising our work.
This will help support that feeling that we are contributing value in our role and others confirmed that.

*Change your perspective*

> "We don't attach to people or things, we attach to uninvestigated concepts that we believe to be true in the moment" - Byron Katie

We are hindered by our fear of being exposed as a fraud, but usually we don't have the proof that confirms that is the case. 
We often wrongly assume and interpret actions of others as a direct cause and affect to things we have done or said. 
This is because we are viewing the situation from our perspective and only from ours. 

Concentrate on what value your work brings to the subject or community and visualize that success. 
Imagining good things happening can give you the confidence, and motivation, to commit to the task at hand and overcome the fear.

*Working in progress*

We are always learning, improving and progressing. 
Treat our successes as continuously developing projects, adding refinements into each iteration. 
Not only will we be able to record multiple successes but also help acknowledge that perfectionism is impossible and mistakes are opportunities for better learning.

=== Network of Support

We understand the power of a community, the ability to bring people together and with the right direction, and a whole lot of love, we can move mountains. 
So why do we feel we can't have the same mentality to helping ourselves?

During stress of tough times, whether its just a bad day, or more chronic episodes of illness, research has shown that having a strong, though not required to be large, social support network is beneficial to our well being.footnote:[American Pyschological Association, https://www.apa.org/topics/manage-stress-social-support[Manage stress: Strengthen your support network]]
Without a social support network it can feel lonely and isolating which can lead into further depression and anxiety.footnote:[Siv Grav, Ove Hellzèn, Ulla Romild, Eystein Stordal, https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2702.2011.03868.x[Association between social support and depression in the general population: the HUNT study, a cross‐sectional survey]] 
Often it's our social support network, even if we don't think we have one, that first spots there is a change with our behavior before we do.

A social support network is made up of friends, family and peers.footnote:[Mayo Clinic, https://www.mayoclinic.org/healthy-lifestyle/stress-management/in-depth/social-support/art-20044445[Social support: Tap this tool to beat stress]]
Although this is different from a support group, which is more formal and often prescribed, a social support network is something we can develop as part of our community and team structure to help tackle stress, and promote self-care.

Look towards those around you that you have a good relationship with and feel that you can confide in them. 
When you are feeling stressful or want to simply vent your frustrations, come to lean on your social support network to do so in a safe and healthy way. 
This unburdening of tension helps untangle your emotions, seek clarity on an aspect of decision making or just lightens your mood by the sheer enjoyment of speaking with them.

We may find that those within the community, which we spend most of our time with, grow to be included in our social support network and that each individual provides us with a unique form of support to help in different ways in our lives. 
But also remember that we should also serve as a form of support to others.

The more education and communicating with our members about the benefits of self-care, the more likely we will see it being practiced and encouraged by others. 
This in turns helps create a more caring and accepting atmosphere in the community.
Education can be in the form of discussions promoting self-care, celebrating mental health campaigns.footnote:[Mental Health Foundation https://www.mentalhealth.org.uk/campaigns/mental-health-awareness-week[Mental Health Awareness Week]], adding to the community guidelines when on-boarding team members to speak to the team if their workload, or other aspects is affecting their health.footnote:[Ubuntu https://wiki.ubuntu.com/BuildingCommunity/Burnout/[Ubuntu Burnout]]footnote:[Ubuntu Burnout Help, https://wiki.ubuntu.com/BuildingCommunity/Burnout/Help[Ubuntu Burnout Help]], or organizing training for team members on mental health awareness. 

If you see a member on the team or community showing symptoms of burnout then reach out to them and let them know that you are concerned for their well being.
Identify that you are there to support them and more often they will respond positively and work together to elevate their stress.footnote:[Jono Bacon, _Detecting and Treating Burnout_, "The Art of Community"]

However, it is important to make clear here that if we feel that we are unable to assist a community member's emotional stress beyond our role's capacity, then encourage that they seek professional health advice immediately. 
We may find ourselves feeling guilty we are unable to provide support, but we need to remind ourselves that we are not professional trained and thus could provide, though well intended, ill advice.footnote:[Chartered Management Institute https://www.managers.org.uk/insights/news/2019/september/how-to-talk-about-depression-at-work[How to Talk About Depression at Work]] 
Remember that other emotions affect those around them including how member's stress can affect ours.

Similarly in our own direct reports' one-to-ones ensure you also have regular one-to-ones with your line manager to highlight any problems you have achieving your workload or affecting your well being. 
Be as direct as you are with helping others, that you are with yourself.

## Resources

* *High-Octane Women: How Superachievers Can Avoid Burnout*
+
by _Sherrie Bourg Carter Psy.D_
* https://www.theburnoutproject.com.au/product/burnoutbookpaperback/[Burnout, Your first ten steps]
+
by _Amy Imms M.D_
* *Burn-out : The High Cost of High Achievement*
+
by _Dr Herbert Freudenberger and Geraldine Richelson_
* *Women's Burnout: How to Spot It, How to Reverse It, and How to Prevent It*
+
by _Dr Herbert Freudenberger and Dr Gail North_
* *The Secret Thoughts of Successful Women*
+
by _Dr Valerie Young_
* *The imposter phenomenon in high achieving women: Dynamics and therapeutic intervention.*
+
by _Dr Pauline Clance and Dr Suzanne Imes_
