= Developing a Metrics Plan/Community Metrics
Authors: Ray Paik
Updated: 2020-07-06


== *Why metrics are important in Open Source communities*

=== *Provide objective measures*
For any organization, you want to have a set of objective measurement to help you understand how you are performing. For businesses, it could be things like revenue, new customer aquisitions, costs, etc. that you can look at periodically (e.g. quarter-over-quarter) to see how you are progressing. For open source projects, it is also helpful to have a set of metrics that can help measure the health of your community.  These could include things like number of contributors, how long it takes to close bugs/issues, responsiveness of reviewers, contributor diversity, etc. 

=== *Transparency*
Transparency is a key ingredient in all open source projects, so it is important to have insight into all contributors to your project. This isn't necessarily to rank or highlight the most active contributors. Rather, this is to get a better sense of where the contributions are coming from (e.g. different geography, organizations, etc.). When you start going beyond 20-30 community members, it starts to become more challenging to have a good insight into all contributors if you don't have a good set of metrics. 

=== *Encourage community participation*
Community metrics will not necessarily provide a full picture of the community, but they do offer important insight into the state of the community. For example, metrics can show if there are regular activities on project's code, bugs/issues, documentation, etc. for the project. Also, when people join a new community, they typically struggle with identifying and connecting with more experienced members.  If the metrics dashboard includes a list of active documentation contributors, that could be useful for anyone interested in contributing to project documentation.  Some communities even have a dashboard of _first time_ contributors to highlight new community members. These may seem like small things, but they could go a long way to help new community members onboard into a project and feel welcome. 

=== *Identify potential bottlenecks in the community*
As open source projects grow, you will typically face challenges with responsiveness to community members. For example, code reviews may take longer or you may see a growing backlog of issues. If you have a good set of metrics (e.g. average time to close issues, median time for code review, etc.) that you review on a regular basis, they could serve as early warning signs before you start to have a number of dissatisfied community members. 

== *Choosing the right metrics for your community*
No two open source communities are the same, so it's natural for each community to have their own set of metrics. There are many factors that can influence what metrics are right for your community. In many communities, you often see emphasis on the speed of merging code. However, if your project is in a heavily regulated industry (e.g. energy, medicine, etc.) where decision to merge new fixes/features can take a long time, you probably would not have several different metrics for _code review efficiency_.  

As you are developing a set of community metrics, it is important to work with community members to get their input and have many people contribute to the community metrics. Hearing from a diverse group of the community is important to ensure that the metrics are inclusive and not just focusing on the work of a subset of the community. For example, if internationalization is important for your project, you want to ensure that your metrics reflect internationalization work. It's also a good practice to review the metrics periodically with the community and discuss if any adjustments are needed for your metrics. Even within the same community, you will likely need to evolve your metrics along with the community as your needs change.

== Resourcea for developing metrics for your community

=== *Take advantage of available resources in your software tools*  
In the past, many people wrote complex scripts/queries to get metrics for their communities. Nowadays, most of the software tools (code repositories, forums, issue trackers, wiki's, etc.) that open source projects typically use have APIs, plug-ins or even built-in dashboards that makes it easy collect data for your community. So if you use tools like Discourse, GitHub, GitLab, Jira, or others, you may be able to save a lot of time by reading their documentations prior to implementing a new set of metrics from scratch. 

=== *The CHAOSS project* 
Not surprisingly, there's an open source project that is focused on community metrics. The project is called CHAOSS (Community Health Analytics for Open Source software) and it has community members from academia, companies that participate in many open source projects, open source foundations, and others. If you visit the https://chaoss.community[CHAOSS website], you will find details on metrics across different categories plus implementation examples for many of these metrics.  

If you browse through CHAOSS metrics, you will likely find plenty of metrics (and implementation) that will be applicable to your community. If you have an idea for new metrics that is not yet in CHAOSS, you can also start a discussion on a new metrics in the CHAOSS community. 

=== *Resources/examples from other communities*  
A number of open source communities have good documentation/code for their community dashboards that many other communities can take advantage of. Many readers may be familiar with the https://k8s.devstats.cncf.io/[CNCF dashboard] and you can find details on their `devstats` project for their dashboard in the CNCF's repo at https://github.com/cncf/devstats. 

Another good example is the https://contributors.rubyonrails.org/contributors[Ruby community dashboard] and their https://contributors.rubyonrails.org/faq[FAQ page], which provides good insight into why they developed the dashboard and some of their implementation decisions. 

Some communities publish contribution metrics after each release. Here is a good https://jeanbaptisteaudras.com/en/2020/03/wordpress-5-4-core-contribution-statistics/[example from WordPress] after their recent release, where you will see a lot of good visualizations for where the contrbutions are coming from. 

== Metrics pitfalls

Metrics are certainly important, but there are definitely shortcomings that we need to be aware of. 

- People often measure the most easily measurable in their metrics: This is human nature as we all want to do what's easier. However, you run the risk of neglecting  important aspects of the community if you only focus on easily mesurable metrics in your community. For example, it's often easier to focus on inputs (e.g. number of commits/merge requests/pull requests) compared to outputs (e.g. the impact of a commit/merge request/pull request). Needless to say, ignoring outputs from the community will provide an incomplete picture of the community. 
- Over-reliance on metrics will provide an incomplete insight: No set of metrics will provide a full picture of communities (or any organizations for that matter). Although it is important to have a standardized set of metrics so that you can gauge your community's progress over time, there will always be things that are extremely difficult to measure or quantify. For example, we all want contributors to feel a strong sense of belonging in the community and enjoy collaborating with other community members.  Whether this is happening or not would be difficult to quantify, but you still want to have a good sense on this aspect of community health even if it requires other means besides metrics collections. 
- Ignoring intrnsic motivation: People often join (especially volunteer) organizations because they are intrincically motivated. For example, they strongly identify with group's mission or enjoy a sense of belonging with other members. If there is too much emphasis on people's contribution (or input) in metrics, you run the risk of losing sight of why people joined the organization in the first place. Most contributors in open source communities are volunteers who contribute in their own time, so ignoring their intrinscic motivation can often lead to negative consequences in the community. 

Following are some examples of poor uses of metrics in open source communities. 

- Gaming contribution metrics: This usually happens when metrics are used as a main (or even a sole) basis for recognition in the community. Not suprisingly you will see behaviors like people submitting multiple commits/merge requests/pull requests for trvial changes when they could have accomplished the same thing with a single commit/merge request/pull request. 
- Vanity metrics: You also see vanity metrics outside of open source. A good example is placing too much emphasis on things like the number of social media followers. As it is in social media, quantity isn't everything. Also, if you want to ensure that community members' intrinsic motivation is satisfied in the community vanity metrics is definitely not a good way to go. 
- Making comparisons between open source communities based on a few metrics: Sometimes you will hear things like "Project A had more than 5,000 people in their last  conference" or "Project B has 1,000 contributors" and people wanting set similar targets for their community. Before you are tempted to compare your open source community to others, it's important to rememeber that no two open source projects are alike. You may be in a different industry, in different stages of project maturity, or have a different scope. So in most cases, it's going to be challenging to make apples-to-apples comparision between different open source projects. Before you think about wanting 1,000 contributors in your community, you may want to ask basic questions like do you really need 1,000 people to accomplish your project's goals? 
- Too much focus on code contributions: It may be because there are more tools available to capture code activities, but there's a tendency to focus mostly on code contributions in open source communities. However, it is important to remember other valuable contributions such as answering questions on forums, triaging issues, maintaining wiki pages, etc. There should be an effort to ensure that community metrics reflect variety of contributions (both code and non-code) in the community. 


== Metrics dos and don'ts 

Finally, here are some dos and don'ts for open source community metrics. 

=== Dos: 

- Make metrics public: This maybe stating the obvious, but transparency in open source should also extend to metrics. When we develop metrics, it helps to include a diverse group of people in the process so that metrics are inclusive and consider all contributions and not just code. Also, our metrics should evolve along with the community. If any adjustments need to be made for our community metrics, it's likely that we will first get that feedback/suggestion from community members. 

- Use metrics for spotting outliers: Metrics are particularly useful for highlighting areas that aren't doing well. Good examples for this is for things related to throughput such as time it takes for close issues, forum posts to be answered, code review, etc. In these examples, metrics are a great tool that can help identify potential bottlenecks in the community. 

- Use metrics as a starting point for gaining further insight into community health: Metrics may tell you _what_ is happening in your community, but you typically will not know the _why_ just by looking at the numbers. If the metrics shows that the number of first time contributors are declining, you will probably need to have some hallway or phone conversations in order to identify the causes of the decline. Metrics will highlight the symptoms as a starting point, but people will then have to do the work from there. 

=== Dont's: 

- Using metrics as a sole basis for rewards: We already discussed gaming of contribution metrics previously if you only rely on metrics for rewards in the community. In addition, if people percieve that rewards are mostly based on the volume of work (or input) you run the risk of discouraging people who aren't able to devote as much time to the project or even people who are getting started in the community. Community members are not joining open source communities just to do more work and we do not want to lose sight of their intrinsic motivation. 

- Presenting metrics without proper context: Even when you get asked what sounds like a straightforward question like "how many contributors do you have in your community?", it is always helpful to get some context behind the question. Depending on who is asking the question, they're usually asking for something slightly different. For example, the total number of contributors in project's history maybe appropriate in one context, but in another the growth of contributors over a time period maybe what the questioner is really after. Also what do thet mean by contributors? Do they want to include people contributing to internationalization, issue triage, etc.? So before we point people to a set of metrics, it is helpful to understant the context or even motivation behind their question. 

- Ignoring non-metrics: As discussed previously, not everything is easily measurable or quantifiable. Even if we have a well defined and polished metrics dashboard, it should not stop us from continuing to have human conversation with community members to keep a pulse on what is happening in the community and encourage community members to point us to what we are not able to see in our metrics. 

