= Developing a Metrics Plan/Community Metrics
Authors: Ray Paik
Updated: 2020-07-06


== *Why metrics are important in Open Source communities*

=== *Provide objective measures*
For any organization, you want to have a set of objective measurement to help you understand how you are performing. For businesses, it could be things like revenue, new customer aquisitions, costs, etc. that you can look at periodically (e.g. quarter-over-quarter) to measure how you are progressing. For open source projects, it is also helpful to have a set of metrics that can help measure the health of your community.  These could include things like number of contributors, how long it takes to close bugs/issues, responsiveness of reviewers, contributor diversity, etc. 

=== *Transparency*
Transparency is a key ingredient in all open source projects, so it is important to have visibility into everyone that is contributing to your project. This isn't necessarily to rank or highlight the most active contributors. Rather, this is to get a better sense of where the contributions are coming from (e.g. different geography, organizations, etc.). When you start going beyond 20-30 community members, it starts to become more challenging to keep track of all contributors if you don't have a good set of metrics. 

=== *Encourage community participation*
Community metrics will not necessarily provide a full picture of the community, but they do offer important insight into the state of the community. For example, metrics can show if there are regular activities on project's code, bugs/issues, documentation, etc. for the project. Also, when new community members join a new community, they typically struggle with connecting with more experienced members.  For example, a set of metrics dashboard that provides list of active documentation contributors could be handy for anyone interested in contributing to project documentation.  Some communities even have a dashboard of _first time_ contributors to highlight new community members. These may seem like small things, but they could go a long way to help new community members onboard into a project. 

=== *Identify potential bottlenecks in the community*
As open source projects grow, you will typically face challenges with responsiveness to community members. For example, code reviews may take longer or you may see a growing backlog of issues. If you have a good set of metrics (e.g. average time to close issues, median time for code review, etc.)that you review on a regular basis, they could server as early warning signs before you start to have a large number of dissatisfied community members. 


== *Choosing the right metrics for your community*


== Developing metrics for your community

=== Take advantage of APIs, dashboards, plug-ins, etc. that are available in your software tools (e.g. forums, code repositories, issue trackers, wiki’s, etc.)
=== Resources/examples from other communities: Lot of communities have good documentation/code for their dashboards (e.g. CNCF, Ruby, etc.)  
=== The CHAOSS project (https://chaoss.community) develops metrics definition and sample implementation for open source communities. 

== Metrics pitfalls

=== Examples of poor uses of metrics (esp. in Open Source communities). 
=== Shortcomings of metrics


== Metrics dos and don'ts 

=== Dos: Make metric public; use metrics for spotting outliers; Metrics should be used for gaining further insight into community health.
=== Dont's: Using metrics as a sole basis for rewards; presenting metrics without proper context; ignoring non-metrics. 


== Parting thoughts, resources, etc. 
 
=== Your metrics should evolve with your community/Set of metrics you use should not be set in stone.
=== Remember to continue having hallway conversations with the community. 

