= Developing a Metrics Plan/Community Metrics
Authors: Ray Paik
Updated: 2020-07-06


== *Why metrics are important in Open Source communities*

=== *Provide objective measures*
For any organization, you want to have a set of objective measurement to help you understand how you are performing. For businesses, it could be things like revenue, new customer aquisitions, costs, etc. that you can look at periodically (e.g. quarter-over-quarter) to measure how you are progressing. For open source projects, it is also helpful to have a set of metrics that can help measure the health of your community.  These could include things like number of contributors, how long it takes to close bugs/issues, responsiveness of reviewers, contributor diversity, etc. 

=== *Transparency*
Transparency is a key ingredient in all open source projects, so it is important to have visibility into everyone that is contributing to your project. This isn't necessarily to rank or highlight the most active contributors. Rather, this is to get a better sense of where the contributions are coming from (e.g. different geography, organizations, etc.). When you start going beyond 20-30 community members, it starts to become more challenging to keep track of all contributors if you don't have a good set of metrics. 

=== *Encourage community participation*
Community metrics will not necessarily provide a full picture of the community, but they do offer important insight into the state of the community. For example, metrics can show if there are regular activities on project's code, bugs/issues, documentation, etc. for the project. Also, when new community members join a new community, they typically struggle with connecting with more experienced members.  For example, a set of metrics dashboard that provides list of active documentation contributors could be handy for anyone interested in contributing to project documentation.  Some communities even have a dashboard of _first time_ contributors to highlight new community members. These may seem like small things, but they could go a long way to help new community members onboard into a project. 

=== *Identify potential bottlenecks in the community*
As open source projects grow, you will typically face challenges with responsiveness to community members. For example, code reviews may take longer or you may see a growing backlog of issues. If you have a good set of metrics (e.g. average time to close issues, median time for code review, etc.) that you review on a regular basis, they could server as early warning signs before you start to have a large number of dissatisfied community members. 

== *Choosing the right metrics for your community*
No two open source communities are the same, so it's natural for each community to have their own set of metrics. There are many factors that can influence what metrics are right for your community. In many communities, you often see emphasis on the speed of merging code. However, if your project is in a heavily regulated industry (e.g. energy, medicine, etc.) where decision to merge new fixes/features can take a long time, you probably would not have several different metrics for _code review efficiency_.  

As you are developing a set of community metrics, it is important to work with community members to get their input and have many people contribute to your community metrics. Hearing from a diverse group of the community is important to ensure that the metrics are inclusive and not just focusing on the work of a subset of the community. For example, if internationalization is important for your project, you want to ensure that your metrics reflect internationalization work. It's also a good practice to review the metrics periodically with the community and discuss if any adjustments are needed for your metrics. Even within the same community, you will likely need to evolve your metrics along with the community as your needs change.

== Developing metrics for your community

=== *Take advantage of available resources in your software tools*  
In the past many people had to write complex scripts/queries to get metrics for their communities. Nowadays, most of the software tools (code repositories, forums, issue trackers, wiki's, etc.) that open source projects use have APIs, plug-ins or even built-in dashboards that makes it easy collect data for your community. So if you use tools like Discourse, GitHub, GitLab, Jira, or others, you may be able to save a lot of time by reading their documentations prior to implementing a new set of metrics from scratch. 

=== *The CHAOSS project* 
Not surprisingly, there's also an open source project that is focused on community metrics. The project is called CHAOSS (Community Health Analytics for Open Source software) and it has community members from academia, companies that participate in many open source projects, open source foundations, and others.  On the CHAOSS website (https://chaoss.community), you will find details on metrics across different categories plus implementation example for many of these metrics.  

If you browse through CHAOSS metrics, you will likely find plenty of metrics (and implementation) that will be applicable to your community. If you have an idea for new metrics that is not yet in CHAOSS, you can always start a discussion on a new metrics in the CHAOSS community. 

=== *Resources/examples from other communities*  
A number of open source communities have good documentation/code for their community dashboards that many other communities can take advantage of. Many readers may be familiar with the CNCF dashboard is at https://k8s.devstats.cncf.io/ and you can find details on their `devstats` project for their dashboard in the CNCF's repo at https://github.com/cncf/devstats. 

Another good example is the Ruby community dashboard at https://contributors.rubyonrails.org/contributors and their FAQ page (https://contributors.rubyonrails.org/faq) provides good insight into why they developed the dashboard and some of their implementation decisions. 

== Metrics pitfalls

=== Examples of poor uses of metrics (esp. in Open Source communities). 
=== Shortcomings of metrics


== Metrics dos and don'ts 

=== Dos: Make metric public; use metrics for spotting outliers; Metrics should be used for gaining further insight into community health.
=== Dont's: Using metrics as a sole basis for rewards; presenting metrics without proper context; ignoring non-metrics. 


== Parting thoughts, resources, etc. 
 
=== Your metrics should evolve with your community/Set of metrics you use should not be set in stone.
=== Remember to continue having hallway conversations with the community. 

