= Events: The life force of open source
Donna Benjamin
2020-01-07

People who make free and open source software often come together in time and space to collaborate on projects that matter to them. These gatherings, both large and small, are very important to the ongoing growth and success of open source communities.

Open source events can include regular local meetups and large international conventions, but they serve the same purpose. They give members of these communities an opportunity to meet, collaborate, and form lasting friendships.

Most development and collaboration in open source software projects happens online, in mailing lists, chat channels, and issue trackers. It can be easy to misinterpret the written word, and misunderstandings lead to unnecessary conflict. The relationships formed at open source events go a long way toward mitigating this kind of friction.

Biella Coleman is an anthropologist who studied the world of hackers. She wrote about https://research.steinhardt.nyu.edu/scmsAdmin/uploads/005/553/83.1.coleman.pdf[the "lifeworld" of hacker conferences] and documented the celebration of community that goes on there, and this also applies to most open source community events.

Good work gets done, but it is the social aspect that creates a foundation for future work, for building trust, and for collaboration that elevates an open source gathering to something more than it seems.

Events accelerate innovation in open source projects. Alongside the usual conference fare of talks and workshops, something like a hackfest or contribution sprint is another common feature. This is where space is made available with tables, WiFi, power, and sometimes even free refreshments. Attendees are invited to work together on the project at hand. Such time and space gives people an opportunity to collaborate to drive a project forward. Quick hallway conversations can turn into experiments in code that lead to new features. Given the opportunity to collaborate through pair programming, developers may bust gnarly bugs that proved elusive online.

Many open source events go to considerable effort to record conference sessions, thereby creating an archive of knowledge and experience that can be reviewed long after the event has passed. This increases the reach and impact of a speaker's efforts and ideas, and makes their content accessible to those who may not have been able to attend.

Alongside work on the project itself, these events also create marketplaces for people to meet, and connect. Jobseekers meet employers, maintainers find contributors, and projects find sponsors. Networking is just as important in open source, as it is in other professional fields.

Like a greenhouse creates an environment where life can flourish, events can create environments where open source communities can flourish. People with a unified interest share what they know, test ideas, and work together to achieve agreed goals. 

Here's a brief list of some of the largest and longest-running events happening around the world. These are great places to grow knowledge, and understanding of the technology, and also to find ways to get involved and contribute. Descriptions in quotes are directly from the conference sites or promotional materials:

- "OSCON provides complete coverage of open source technology and projects, no matter the origin or affiliation. Rather than focus on a single language or aspect, our program solely focuses on projects in areas of innovation including cloud, AI, infrastructure, blockchain, edge computing, architecture, and emerging languages." https://conferences.oreilly.com/oscon/oscon-or[OSCON]

- "FOSDEM is organised by the community for the community. It gives free and open source software developers and communities a place to meet, to be informed about the latest developments in the free and open source world; and attend interesting talks and presentations on various topics by project leaders and committers." https://fosdem.org/[FOSDEM]

- "FOSSASIA Summit is the premier Free and Open Source technology event in Asia for developers, start-ups, and contributors. Projects at FOSSASIA range from open hardware, to design, graphics and software. FOSSASIA was established in 2009. Previous events took place in Vietnam, Thailand, Cambodia, China and India." https://summit.fossasia.org/[FOSSASIA]

- The Open Source Festival in Africa is "a high profile event that would attract student delegates, developers, designers and corporate organizations on a large scale with a series of talks, workshops, and awareness of open-sourced developer tools." https://festival.oscafrica.org/[OSCAfrica]

- Linux.conf.au has been running for 20 years in Australia and New Zealand. It is arguably the leading annual event for the broader Free and Open Source Software community in Australasia. http://linux.conf.au/[linux.conf.au]

- DrupalCon serves one of the largest open source communities in the world. Developers, designers, content strategists, editors, translators, end-users and more come together, twice a year, at this event. https://events.drupal.org/[DrupalCon]

- "WordCamps are casual, locally-organized conferences covering everything related to WordPress, the free and open source personal publishing software that powers over 75 million sites on the web." https://central.wordcamp.org/about/[WordCamp]

- ApacheCon is the "place to learn the latest about Apache projects and developing Open Source innovations and communities 'The Apache Way.' ApacheCon is also where Apache projects come to build stronger communities, forge bonds amongst projects, and deepen connections with users and contributors." https://www.apachecon.com/[ApacheCon]

- "Wikimania is the annual conference celebrating all the free knowledge projects hosted by the Wikimedia Foundation. Hundreds of volunteers and Free Knowledge leaders from around the world gather to discuss issues, report on new projects and approaches, and exchange ideas." https://wikimania.wikimedia.org/wiki/Wikimania[Wikimania]

- The Linux Foundation also runs a series of events around the world aimed at building sustainable ecosystems around open source projects to accelerate technology development and industry adoption. https://events.linuxfoundation.org/[Linux Foundation Events]

We would also be remiss not to mention https://flocktofedora.org/[Flock], the annual conference for the Fedora Project's contributor community. Flock alternates between Europe and North America and brings together the contributor community to communicate the Fedora strategy, plan the strategy for the future, and build connections.

And, of course, https://www.redhat.com/en/summit/about/why-attend[Red Hat Summit], Red Hat's annual gathering of customers, partners, users, and (of course) Red Hatters. 

Open source is global. Somewhere on planet Earth, events are happening almost daily that bring our communities together, and propel our projects into the future. Whether it's to learn something new, share experiences, teach key skills, meet with peers, or make new friends, the value we find, and build together, is incalculable. 
