= Onboarding
Authors: Karsten Wade <kwade@redhat.com>, Josh Berkus <jberkus@redhat.com>, Brian Proffitt <bproffit@redhat.com>, Dave Neary <dneary@redhat.com>
Updated: 2020-03-30

== Introduction

In many ways, onboarding in a new open source community is a lot like onboarding for a new job. You need to get familiar with new people, new tools, new processes, etc. so that you feel comfortable in your new settings and can start contributing. However, there are a number of ways that onboarding in open source communities can present different challenges. 

The first challenge in open source is that you work in an asynchronous and remote environment. One of the great perks of a traditional office environment is that you  are close to your co-workers and managers for face to face interactions and you can easily reach out to them for quick questions. In contrast, when you join a new open source community, you will likely work with other community members in different georgraphies and time zones. So unless there are good onboarding materials such as documentation, video tutorials, wiki pages, and other resources, it's going to be more challenging to get started in open source communties even for experienced self starters. 

Another related challenge is that working in asynchronous/remote environment can exacerbate the imposter syndrome that people typically experince when they start new jobs. When it's more difficult to get real time help or feedback, people can get stuck with simple tools issues and feel less confident about their work. So good onboarding experience in open source communities is crucial for newcomers not to feel discouraged in their early days in the community. 

Finally, no two open source communities are the same. Even for seasoned open source contributors, when they join a new community they will need to get familiar with new tools, new processes, and even new terminologies. Depending on the community, terms like contributors, community members, projects, etc. may mean something different and new community members can feel lost unless these are well defined or documented.   


== Tools for onboarding

* Landing page
* Orientation events for newcomers
* Communication channels
* Issues for new contributors

== People to help with onboarding

* Coaches/mentors
* A team/working group focused on onboarding.

== Mentorship



== Resources
