= Onboarding
Authors: Karsten Wade <kwade@redhat.com>, Josh Berkus <jberkus@redhat.com>, Brian Proffitt <bproffit@redhat.com>, Dave Neary <dneary@redhat.com>
Updated: 2020-03-30

== Introduction

In many ways, onboarding at a new open source community is a lot like onboarding for a new job. You need to get familiar with new people, new tools, new processes, etc. so that you feel comfortable in your new settings and can start contributing. However, there are a number of ways that onboarding in open source communities can present different challenges. 

The first challenge in open source is that you work in an asynchronous and remote environment. One of the nice perks of traditional office environment is that you  are close to your co-workers and managers for face to face interactions and you can easily reach out to them for quick questions. 

* Imposter syndrome
* Each open source community is different

== Tools for onboarding

* Landing page
* Orientation events for newcomers
* Communication channels
* Issues for new contributors

== People to help with onboarding

* Coaches/mentors
* A team/working group focused on onboarding.

== Mentorship



== Resources
