= Presenting The Open Source Way
Author: Karsten Wade <quaid@iquaid.org>
Updated: 2020-10-27

An English idiom says, "There is a method to my madness.".footnote:[From "Hamlet" by William Shakespeare, Act 2 Scene 2: Polonius (aside) "Though this be madness, yet there is method in `t"]
Most of the time, the things we do make absolutely no sense to outside observers.
They look like sheer madness.
But for those inside that messiness—inside that whirlwind of activity—there's a certain regularity, a certain predictability, and a certain motive.
A method.

Open source community management can seem like its own form of incomprehensible madness, especially to someone who's unfamiliar with how open source software gets made, or those who find themselves staring down the prospect of having to coordinate others to join in making it.

What this guide hopes to provide is some insight into an ever-evolving methodology.
What are your preferences for practicing the open source way?

But beyond that, this work is really digging into the question of _why_ someone might do the work this way.
Why use this or that method to organize the madness?

So from this introduction you should take two important points:

. There is a _what_, a _how_, and a _why_ to the practice of successfully and sustainably creating and maintaining open source software.
. This guide distills opinions from a sizeable group of open source practitioners, the kind of people always having to answer the question of _why we do this open source thing the way we do it_.

In particular, this guide is a living document that endeavors to gather and spread a diverse group of voices who are similarly (and somewhat-opinionatedly) collecting the best ways to create and manage an open source software community.

These voices are all part of https://theopensourcway.org[this community of practice around open source software community management].

== The shape of things, i.e., assumptions we are making

When you look at the table of contents for this guide, notice how the flow of focus goes from the user, to the participant, to the contributor.

This arrangement specifically tracks our view of how a community comes about and grows. And it all starts with a need.

. A person or persons needing a solution creates the first iteration of the software.
. Other people with similar needs start using it, forming the core of the userbase.
. From the userbase arise people who are enthusiasts of the software and things about/around it.
. Eventually arising from the users and the enthusiasts come people who are interested and have grown capable of contributing to the software in some way.

Thus, the primary and continual focus for a project is to _take good care of your users_, for some of them will become your contributors, and you want them to do it out of love more than anger.

A key element of all this is recognizing the value in contributions of all types, at all levels.
Rather than valorizing only a single type of contribution, the best practice is to treat all manner of gifts to the project as equal.
These contributions comprise content and code, hours and effort, and all manner of broad contributions for the project via events, discussion forums, infrastructure maintenance, and so on.

When you lower barriers to participation, you make your project welcoming at all levels.
This doesn't mean you _remove all barriers_—just lower most of them appropriately.
Appropriate barriers are necessary for someone receiving keys to systems, for example, and these barriers are different from those allowing only certain participants to contribute a help article or a patch to the configuration management system.

=== Our core opinion

There is an opinion at the core of this work, that explains how the content is laid out, how the steps on the path revealed so that you can find yourself wherever you are in your journey of open source practice.

____
Focus on your end-users and lower the barriers to participation all around.

Contributors arise from participants, who all started as users.

Make your software wildly successful by having a user-centric initiative, while making the community open and welcoming those users come looking to see what is going on the creation/contribution side 
____

The pathway of this guidebook therefore is:

1. *Attract users* to your software because it solves the problems they have.
2. *Guide participants* who care about open source and sharing good solutions so that they can be effective enthusiasts for your software.
3. *Grow contributors* from this rich, fertile user and enthusiast base, by making sure when any of those folks look into how the software is made, they see themselves represented and can imagine how they could fit in, too.
Make sure when they get to the contributor party, the barriers are clearly lowered and welcoming.

It's one thing to let people know about your great dance party.
It's another thing to empower those dancers to advocate for your way of throwing a dance party.
It's a very great thing to make the dance party able to evolve to welcome all manner of music and dance from the world around us.

To get the dancers who see your poster and show up in the first step to stick around, it helps if they can see right away that this is a place for them and theirs, too.

In considering this pathway, you can see there is no emphasis on expertise or even existing skills relevant to the project more than curiosity and willingness to try the software, to care about the software, and to help create the software.
This does not mean that people don't bring skills to the project; they do, many of them right from first point of contact with the project.
But it is easier to teach skills than to teach someone to truly care about your project.

In this journey, there are many best practices we recommend, including how to put together a plan for measuring your community's progress.
We also list some specific areas to be careful of and watch out for, including a robust discussion on self-care and mental health considerations for community managers themselves.

Our best way of more-deeply conveying all this information is with stories.
Aside from stories that naturally arise in the body of the chapter, there are other areas in the guidebook and in https://theopensourceway[The Open Source Way community] to gather all these stories of why. 

== Structure of this guide

Each section of this guide consists of one or more chapters.
 
A chapter is a discrete discussion of a topic or a closely-related set of topics.
// Those topics are discussed in terms of a principle (what), implementation of that principle (how), and examples of why that principle is followed or recommended.
//This principle/implementation/example, or PIE, approach helps makes chapters consistent for reading.

The idea is that you can open and read a chapter as a stand-alone experience without needing to read the rest of the guide to understand and act from the material in that chapter.
// Having the PIE consideration helps as reader find themselves in the guide at any point.

A chapter consists of several parts:

* An introduction
* Primary material, written in third person POV, focusing on a balance of what, how, why content. The examples (stories) told here are brief and in the third person.
* Expanded stories come at the end of the chapter, and are one or more stories from the chapter author(s). These may be written in the first person—that may be the most effective way to make the point in many cases. These stories are modular, in that another story that makes a similar point but from a different situation can be used instead.
** The idea is to start with a base story or set of stories in a chapter, and supplement or substitute other stories that are contributed to the project, such as through the interview effort.
* Each chapter contains a lexicon at the end that defines the special usage for terms within that chapter.

Finally, we're collecting stories from practitioners of the open source way, stories we know tend to illustrate more than one principle in action.
Stories not interspersed into chapters will be collected at the end (for your endless uses).

== A community of practice always rebuilidng itself

What you are reading here is just one facet of the growing body of principles, implementations, and examples that this community is gathering, cultivating, and maintaining.

In the end, it's just one way to pull this material together (one method, you might say, of organizing the madness).
We'll be updating this guide. We'll be issuing similar, new guides. And we'll experiment with other ways to understand and present this material.

But at the core—in addition to the _what_ and the _how_ that benefit your open source community—you will also learn to understand the _why_, and be able to spread those stories wherever you go.

*TBD* _Content here needs to be confirmed with the format of the actual chapters we're releasing.
Then it needs a nice concluding sentence, if this one is insufficient._
*TBD*
