= The Open Source Way Publishing Process

The workflow of The Open Source Way is largely dependent on the functionality of the GitHub platform. GitHub is a web-based distributed version control tool that enables content creators build and collaborate on text-based creations (code, prose) wherever they can connect to the Internet.

The Open Source Way process will be divided into two distinct parts: contribution and editorial.

Contribution is the process of initial creation; it will take full advantage of GitHub's distributed features, adding  content to GitHub in a separate branch, and then merging into the main content of The Open Source Way.

Editorial is the process or perfecting the created content, via various editing passes. This can be done primarily within GitHub's issue-tracking tools, within the GitHub interface. 

Before beginning work on The Open Source Way, it is important for all participants to have a https://github.com/[GitHub account] if they don't have already. All work done on The Open Source Way will be done within the https://github.com/theopensourceway/guidebook[guidebook repository] of the https://github.com/theopensourceway[The Open Source Way organization].


== Contributing to The Open Source Way

Contributing a new chapter to The Open Source Way is relatively easy. Content can be created locally on any system and then inserted with the GitHub web interface.

. Click create New File
. Add a file name in the name field
. Copy the text into the Edit new file field
. In the `Commit new file` section, add a short commit message.
. In the `Comment` field, add a short message with the number of the issue associated with the chapter. "Per #_XX_"
. Click the `Create a new branch for this commit and start a new pull request` radio button. You can use the suggested branch name.
. Click `Propose New File`. The `Open a Pull Request` window will open.
. Click the gear icon in the Reviewers pane in the right column of the page.
. Choose the reviewer recommended to you upon initial consultation about the chapter.
. Click `Create pull request`.

The chapter will be submitted for initial review. If it meets inclusion criteria, it will be merged into the Main branch.

== Reviewing an initial contribution

When receiving a review request for an initial contribution, a reviewer should use The Open Source Way guidelines to approve the chapter for further editing. 

When the review is complete and the pull request is merged, the reviewer should perform one more additional step, so subsequent editors can find the file quickly.

. Open the merged file in GitHub.
. Copy and paste the full URL for the file into the relevant issue's comment section.
. Click `Comment`.

== Editing in The Open Source Way

